"""Render the sourced catalog into browsable static pages and a small search index."""
from pathlib import Path
import argparse
import html
import json
import re
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
BASE = '/study-abroad-handbook/'
SECTIONS = [('overview', '专业说明'), ('admissions', '入学条件'), ('fees', '学费与费用'), ('outcomes', '毕业生情况')]

def esc(value):
    return html.escape(str(value), quote=True)

def route(country, university=None, program=None):
    parts = ['catalog', country]
    if university: parts.append(university)
    if program: parts.append(program)
    return '/'.join(parts) + '/'

def link(path, text, cls=''):
    return f'<a class="{cls}" href="{BASE}{path}">{esc(text)}</a>'

def load_catalog():
    countries, universities, programs = [], [], []
    for file in sorted((ROOT / 'data/catalog').glob('*.json')):
        data = json.loads(file.read_text())
        countries.append(data['country'])
        universities.extend(data['universities'])
        programs.extend(data['programs'])
    assert countries and programs, 'Catalog must contain real entries'
    for group in (countries, universities, programs):
        ids = [x['id'] for x in group]
        assert len(ids) == len(set(ids)), f'Duplicate IDs: {ids}'
        assert all(re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', x) for x in ids)
    cm, um = {c['id']: c for c in countries}, {u['id']: u for u in universities}
    for u in universities:
        assert u['country_id'] in cm and u['website'].startswith('https://')
    for p in programs:
        assert p['university_id'] in um
        for key in ['name', 'name_en', 'degree', 'subject', 'intake', 'duration', 'entry_summary', 'tuition_summary', 'outcomes_summary', 'checked_at']:
            assert isinstance(p[key], str) and p[key].strip(), f'{p["id"]}: missing {key}'
        assert re.fullmatch(r'\d{4}-\d{2}-\d{2}', p['checked_at'])
        sources = {s['id']: s for s in p['sources']}
        assert sources and len(sources) == len(p['sources'])
        for s in sources.values():
            assert re.fullmatch(r'[a-zA-Z0-9-]+', s['id']), s['id']
            assert urlsplit(s['url']).scheme == 'https' and s['title'] and s['supports']
            assert s['checked_at'] == p['checked_at']
        cited = set()
        for key, _ in SECTIONS:
            assert p['sections'][key], f'{p["id"]}: empty section {key}'
            for fact in p['sections'][key]:
                assert fact['label'] and fact['text'] and fact['source_ids']
                assert set(fact['source_ids']) <= sources.keys(), f'{p["id"]}: broken source reference'
                cited.update(fact['source_ids'])
        assert cited == sources.keys(), f'{p["id"]}: unused sources {sources.keys() - cited}'
    return countries, universities, programs

def front(title, wide=False):
    hidden = ['toc', 'navigation'] if wide else ['toc']
    return '---\ntitle: ' + title + '\nhide:\n' + ''.join('  - '+x+'\n' for x in hidden) + '---\n\n<!-- Generated by scripts/render_catalog.py; edit data/catalog/*.json. -->\n\n'

def crumbs(items):
    return '<nav class="catalog-crumbs" aria-label="浏览路径">' + ' <span aria-hidden="true">/</span> '.join(link(p,t) if p is not None else f'<span aria-current="page">{esc(t)}</span>' for p,t in items) + '</nav>\n\n'

def program_card(p, u, c):
    return f'''<article class="program-card" data-program-id="{p['id']}">
<div class="program-meta"><span>{esc(c['name'])} · {esc(u['city'])}</span><span>{esc(p['subject'])}</span></div>
<p class="program-school">{link(route(c['id'],u['id']), u['name'])}</p>
<h3>{link(route(c['id'],u['id'],p['id']), p['name'])}</h3>
<p class="program-english">{esc(p['name_en'])}</p>
<p class="program-cohort">{esc(p['intake'])} 入学 · {esc(p['degree'])} · {esc(p['duration'])}</p>
<dl class="program-facts"><dt>入学</dt><dd>{esc(p['entry_summary'])}</dd><dt>学费</dt><dd>{esc(p['tuition_summary'])}</dd><dt>毕业</dt><dd>{esc(p['outcomes_summary'])}</dd></dl>
{link(route(c['id'],u['id'],p['id']), '查看条件、费用与去向 →', 'program-open')}
</article>'''

def university_card(u, c, programs):
    ps = [p for p in programs if p['university_id'] == u['id']]
    return f'''<article class="university-card"><p class="catalog-eyebrow">{esc(u['city'])} · {len(ps)} 个已收录专业</p><h2>{link(route(c['id'], u['id']), u['name'])}</h2><p class="university-english">{esc(u['name_en'])}</p><ul>''' + ''.join(f'<li>{link(route(c["id"],u["id"],p["id"]),p["name"])}</li>' for p in ps) + f'</ul>{link(route(c["id"],u["id"]),"查看大学与全部专业 →","program-open")}</article>'

def generate():
    countries, universities, programs = load_catalog()
    order = {'uk':0, 'australia':1, 'singapore':2}
    countries.sort(key=lambda c: order.get(c['id'], 99))
    cm, um = {c['id']:c for c in countries}, {u['id']:u for u in universities}
    universities.sort(key=lambda u: order.get(u['country_id'],99))
    programs.sort(key=lambda p: (order.get(um[p['university_id']]['country_id'],99), universities.index(um[p['university_id']])))
    outputs = {}
    cards = '\n'.join(program_card(p, um[p['university_id']], cm[um[p['university_id']]['country_id']]) for p in programs)
    home = front('大学与专业查询', True)
    home += '<div class="catalog-home">\n<p class="catalog-eyebrow">面向中国大陆学生的海外本科目录</p>\n\n# 查大学，找专业\n\n按国家进入大学，再查看具体专业；也可以直接搜索学校或专业名称。\n\n'
    home += '<div class="country-grid">\n'
    for c in countries:
        us = [u for u in universities if u['country_id'] == c['id']]
        ps = [p for p in programs if p['university_id'] in {u['id'] for u in us}]
        home += f'<a class="country-card country-{c["id"]}" href="{BASE}{route(c["id"])}"><span class="country-en">{esc(c["name_en"])}</span><strong>{esc(c["name"])}</strong><span>{len(us)} 所大学 · {len(ps)} 个专业 <b aria-hidden="true">↗</b></span></a>\n'
    home += '</div>\n\n<div id="program-finder" data-catalog-url="assets/data/catalog-index.json">\n<div class="finder-heading"><h2>直接找专业</h2><span>首批 {}</span></div>\n'.format(' · '.join([f'{len(countries)} 个国家',f'{len(universities)} 所大学',f'{len(programs)} 个专业']))
    home += '''<form class="catalog-filters" role="search" aria-label="筛选大学与专业">
<label class="catalog-query">搜索学校或专业<input id="catalog-query" name="q" type="search" placeholder="例如：计算机、NUS、曼彻斯特" autocomplete="off"></label>
<label>国家<select id="catalog-country" name="country"><option value="">全部国家</option>'''
    home += ''.join(f'<option value="{c["id"]}">{esc(c["name"])}</option>' for c in countries)
    home += '</select></label><label>大学<select id="catalog-university" name="university"><option value="">全部大学</option>' + ''.join(f'<option value="{u["id"]}" data-country="{u["country_id"]}">{esc(u["name"])}</option>' for u in universities) + '</select></label><label>专业方向<select id="catalog-subject" name="subject"><option value="">全部方向</option>' + ''.join(f'<option value="{esc(s)}">{esc(s)}</option>' for s in sorted({p['subject'] for p in programs})) + '</select></label><button type="reset">清除筛选</button></form>\n'
    home += '<noscript><style>.catalog-filters{display:none}</style><p>可通过国家入口和下面的专业链接直接浏览。启用 JavaScript 后可使用即时筛选。</p></noscript>'
    home += f'<p class="catalog-status" id="catalog-status" role="status" aria-live="polite">显示全部 {len(programs)} 个专业。入学年度与费用币种见各项目。</p><p id="catalog-empty" hidden>没有匹配的已收录专业。可以减少筛选条件，或清除筛选查看全部项目。</p><div class="program-grid" id="catalog-results">{cards}</div>\n</div>\n\n'
    home += '<div class="catalog-footnote"><strong>收录范围与数据口径</strong><p>目前为三个国家的本科项目首批目录，尚未覆盖全部大学与专业。不同项目的入学年可能不同；学费按国际生口径记录，毕业统计注明调查范围，缺少的数据会明确标出。资料核验：2026-09-12。</p>' + link('about/catalog-data/','查看数据说明') + ' · ' + link('tools/budget/','计算全程预算') + ' · ' + link('start/undergraduate/','申请准备指南') + '</div>\n</div>\n'
    # Markdown needs markdown="1" only on containers containing Markdown headings.
    home = home.replace('<div class="catalog-home">','<div class="catalog-home" markdown="1">')
    outputs['docs/index.md'] = home
    index = []
    for c in countries:
        us = [u for u in universities if u['country_id'] == c['id']]
        body = front(c['name']+'大学与专业', True) + crumbs([('', '大学与专业'),(None,c['name'])])
        body += f'# {c["name"]}大学与专业\n\n先选择大学，再进入专业查看入学条件、国际生学费和毕业生情况。当前收录 {len(us)} 所大学。\n\n<div class="university-grid">\n'
        body += '\n'.join(university_card(u,c,programs) for u in us) + '</div>\n\n'
        body += link('?country='+c['id']+'#program-finder','筛选这个国家的全部专业 →','md-button') + '\n'
        outputs['docs/'+route(c['id'])+'index.md'] = body
        for u in us:
            ps = [p for p in programs if p['university_id']==u['id']]
            body = front(u['name'],True) + crumbs([('', '大学与专业'),(route(c['id']),c['name']),(None,u['name'])])
            body += f'# {u["name"]}\n\n<p class="university-title-en">{esc(u["name_en"])}</p><p class="university-location">{esc(c["name"])} · {esc(u["city"])}</p>\n\n'
            if u.get('aliases'): body += '<p class="university-aliases">常用名称或简称：' + esc(' · '.join(u['aliases'])) + '</p>\n\n'
            body += f'<p><a href="{esc(u["website"])}">大学官方网站 ↗</a> · 已收录 {len(ps)} 个本科专业</p>\n\n## 选择具体专业\n\n<div class="program-grid">\n' + '\n'.join(program_card(p,u,c) for p in ps) + '</div>\n\n'
            body += '入学条件与学费按下面每个项目的入学年度查看；毕业调查的统计年份和对象另行注明。\n'
            outputs['docs/'+route(c['id'],u['id'])+'index.md'] = body
            for p in ps:
                body = front(u['name']+' · '+p['name']) + crumbs([('','大学与专业'),(route(c['id']),c['name']),(route(c['id'],u['id']),u['name']),(None,p['name'])])
                body += f'<p class="catalog-eyebrow">{esc(u["name"])} · {esc(p["degree"])} · {esc(p["subject"])}</p>\n\n# {p["name"]}\n\n<p class="program-title-en">{esc(p["name_en"])}</p>\n\n'
                body += '<div class="program-at-a-glance">' + ''.join(f'<div><span>{label}</span><strong>{esc(value)}</strong></div>' for label,value in [('入学年度',p['intake']),('学制',p['duration']),('国际生学费',p['tuition_summary'])]) + '</div>\n\n'
                body += '<nav class="program-jumps" aria-label="专业详情章节">' + ''.join(f'<a href="#{key}">{title}</a>' for key,title in SECTIONS) + '</nav>\n\n'
                for key,title in SECTIONS:
                    body += f'## {title} {{#{key}}}\n\n'
                    for fact in p['sections'][key]:
                        body += f'### {fact["label"]}\n\n<p class="catalog-fact">{esc(fact["text"]).replace(chr(10),"<br>")}</p>\n<p class="fact-sources">'
                        body += ' · '.join(f'<a href="#source-{sid}">依据 {list(s["id"] for s in p["sources"]).index(sid)+1}</a>' for sid in fact['source_ids']) + '</p>\n\n'
                body += '## 官方来源与核验记录 {#sources}\n\n'
                body += f'资料核验：**{p["checked_at"]}**。课程招生年份与毕业调查年份分别记录；历史毕业结果不表示未来个人结果。\n\n'
                for i,s in enumerate(p['sources'],1):
                    body += f'<div class="catalog-source" id="source-{s["id"]}"><span class="source-number">{i:02d}</span><div><a href="{esc(s["url"])}">{esc(s["title"])} ↗</a><p>{esc(s["supports"])}</p><small>{esc(urlsplit(s["url"]).netloc)} · 核验 {s["checked_at"]}</small></div></div>\n'
                body += '\n' + link(route(c['id'],u['id']),'← 返回'+u['name']) + ' · ' + link('tools/budget/','用已确认费用计算全程预算') + '\n'
                outputs['docs/'+route(c['id'],u['id'],p['id'])+'index.md'] = body
                index.append({k:p[k] for k in ['id','university_id','name','name_en','degree','subject','intake','duration','entry_summary','tuition_summary','outcomes_summary']} | {'country_id':c['id'],'country_name':c['name'],'university_name':u['name'],'university_name_en':u['name_en'],'aliases':u.get('aliases',[]),'url':route(c['id'],u['id'],p['id'])})
    outputs['docs/assets/data/catalog-index.json'] = json.dumps(index,ensure_ascii=False,indent=2)+'\n'
    nav = []
    for c in countries:
        nav.append(f'  - {c["name"]}:')
        nav.append(f'      - 大学列表: {route(c["id"])}index.md')
        for u in [u for u in universities if u['country_id']==c['id']]:
            nav += [f'      - {u["name"]}:', f'          - 大学概览: {route(c["id"],u["id"])}index.md']
            for p in [p for p in programs if p['university_id']==u['id']]:
                nav.append(f'          - {p["name"]}: {route(c["id"],u["id"],p["id"])}index.md')
    config = (ROOT/'mkdocs.yml').read_text()
    config = re.sub(r'  # CATALOG_NAV_START\n.*?  # CATALOG_NAV_END', '  # CATALOG_NAV_START\n'+'\n'.join(nav)+'\n  # CATALOG_NAV_END',config,flags=re.S)
    outputs['mkdocs.yml'] = config
    return outputs, (len(countries),len(universities),len(programs))

if __name__ == '__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    outputs, counts = generate()
    outdated=[]
    for name,content in outputs.items():
        path=ROOT/name
        if not path.exists() or path.read_text()!=content:
            if args.check: outdated.append(name)
            else: path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content)
    expected={str((ROOT/name).resolve()) for name in outputs if name.startswith('docs/catalog/')}
    unexpected=[str(p.relative_to(ROOT)) for p in (ROOT/'docs/catalog').rglob('*.md') if str(p.resolve()) not in expected]
    assert not unexpected, f'Orphaned generated pages: {unexpected}'
    if outdated: raise SystemExit('Catalog output is stale: '+', '.join(outdated))
    print(f'Catalog {"checked" if args.check else "rendered"}: {counts[0]} countries, {counts[1]} universities, {counts[2]} sourced programs')
