"""Render the sourced catalog into browsable static pages and a small search index."""
from pathlib import Path
import argparse
import html
import json
import hashlib
import re
from urllib.parse import urlsplit
from catalog_inventory import load_inventories, coverage_text, inventory_markdown
from catalog_research import attach_research, profile_markdown

ROOT = Path(__file__).resolve().parents[1]
BASE = '/study-abroad-handbook/'
RANKING = json.loads((ROOT / 'data/rankings/qs-2027.json').read_text())
SECTIONS = [('overview', '专业说明'), ('admissions', '入学条件'), ('applications', '申请安排'), ('fees', '学费与资助'), ('outcomes', '毕业生情况')]

def esc(value):
    return html.escape(str(value), quote=True)

def route(country, university=None, program=None):
    parts = ['catalog', country]
    if university: parts.append(university)
    if program: parts.append(program)
    return '/'.join(parts) + '/'

def link(path, text, cls=''):
    return f'<a class="{cls}" href="{BASE}{path}">{esc(text)}</a>'

def load_catalog():
    countries, universities, programs = [], [], []
    for file in sorted((ROOT / 'data/catalog').glob('*.json')):
        data = json.loads(file.read_text())
        countries.append(data['country'])
        universities.extend(data['universities'])
        programs.extend(data['programs'])
    assert countries and programs, 'Catalog must contain real entries'
    for group in (countries, universities, programs):
        ids = [x['id'] for x in group]
        assert len(ids) == len(set(ids)), f'Duplicate IDs: {ids}'
        assert all(re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', x) for x in ids)
    cm, um = {c['id']: c for c in countries}, {u['id']: u for u in universities}
    for u in universities:
        assert u['country_id'] in cm and u['website'].startswith('https://')
    ranked = {r['name_en']: r for r in RANKING['rows'] if r['location'] != 'China (Mainland)' and r['rank'] <= 100}
    assert RANKING['edition'] == 2027 and len(RANKING['rows']) == 102
    assert len({r['name_en'] for r in RANKING['rows']}) == 102
    assert hashlib.sha256(json.dumps(RANKING['rows'], ensure_ascii=False, sort_keys=True, separators=(',', ':')).encode()).hexdigest() == RANKING['extracted_rows_sha256']
    assert len(ranked) == 96 and len(universities) == len(ranked)
    assert {u['qs_name_en'] for u in universities} == ranked.keys(), 'QS selection incomplete or contains extras'
    for u in universities:
        row = ranked[u['qs_name_en']]
        assert u['qs_rank'] == row['rank'] and u['qs_rank_display'] == row['rank_display']
        assert u['qs_year'] == 2027 and int(u['qs_rank_display'].lstrip('=')) == u['qs_rank']
        assert cm[u['country_id']]['qs_location'] == row['location']
    for p in programs:
        assert p['university_id'] in um
        for key in ['name', 'name_en', 'degree', 'subject', 'intake', 'duration', 'campus', 'language', 'entry_summary', 'tuition_summary', 'outcomes_summary', 'checked_at']:
            assert isinstance(p[key], str) and p[key].strip(), f'{p["id"]}: missing {key}'
        assert re.fullmatch(r'\d{4}-\d{2}-\d{2}', p['checked_at'])
        sources = {s['id']: s for s in p['sources']}
        assert sources and len(sources) == len(p['sources'])
        for s in sources.values():
            assert re.fullmatch(r'[a-zA-Z0-9-]+', s['id']), s['id']
            assert urlsplit(s['url']).scheme == 'https' and s['title'] and s['supports']
            assert s['checked_at'] == p['checked_at']
        cited = set()
        for key, _ in SECTIONS:
            assert p['sections'][key], f'{p["id"]}: empty section {key}'
            for fact in p['sections'][key]:
                assert fact['label'] and fact['text'] and fact['source_ids']
                assert set(fact['source_ids']) <= sources.keys(), f'{p["id"]}: broken source reference'
                cited.update(fact['source_ids'])
        assert cited == sources.keys(), f'{p["id"]}: unused sources {sources.keys() - cited}'
    programs = load_inventories(ROOT, universities, programs)
    attach_research(ROOT, universities, programs)
    return countries, universities, programs

def front(title, wide=False, program_context=None):
    hidden = ['toc', 'navigation'] if wide else ['toc']
    context = ''.join(key+': '+json.dumps(value,ensure_ascii=False)+'\n' for key,value in (program_context or {}).items())
    return '---\ntitle: ' + json.dumps(title, ensure_ascii=False) + '\n'+context+'hide:\n' + ''.join('  - '+x+'\n' for x in hidden) + '---\n\n<!-- Generated by scripts/render_catalog.py; edit data/catalog, data/program-index or data/program-research. -->\n\n'

def crumbs(items):
    return '<nav class="catalog-crumbs" aria-label="浏览路径">' + ' <span aria-hidden="true">/</span> '.join(link(p,t) if p is not None else f'<span aria-current="page">{esc(t)}</span>' for p,t in items) + '</nav>\n\n'

def rank_badge(u, program=False):
    label = '大学 QS 2027' if program else 'QS 2027'
    return f'<span class="qs-rank">{label} · <strong>{esc(u["qs_rank_display"])}</strong></span>'

def program_card(p, u, c):
    depth = '仅补学校共用资料' if p.get('research_scope') == 'school' else {'detailed':'含详细资料','enriched':'部分专业资料已核实','directory':'目录已核对 · 详情待补'}[p['detail_status']]
    secondary = p['name_en'] if p['name'] != p['name_en'] else p.get('degree_label', p['degree'])
    cohort = p['intake']+' 入学' if p['intake'] != '尚未核实' else '入学年度待核实'
    facts = '<dl class="program-facts">'+''.join('<dt>'+label+'</dt><dd>'+esc(p[key])+'</dd>' for label,key in [('入学','entry_summary'),('学费','tuition_summary'),('毕业','outcomes_summary')])+'</dl>' if p['detail_status']=='detailed' else '<p class="directory-note">'+esc(p['entry_summary'])+'</p>'
    return f'''<article class="program-card" data-program-id="{p['id']}">
<div class="program-meta"><span>{esc(c['name'])} · {esc(u['city'])}</span><span>{esc(p['subject'])}</span></div>
<p class="program-school">{link(route(c['id'],u['id']), u['name'])}</p>
{rank_badge(u, True)} <span class="program-depth">{depth}</span>
<h3>{link(route(c['id'],u['id'],p['id']), p['name'])}</h3>
<p class="program-english">{esc(secondary)}</p>
<p class="program-cohort">{esc(cohort)} · {esc(p['degree'])}</p>
{facts}
{link(route(c['id'],u['id'],p['id']), '查看条件、费用与去向 →', 'program-open')}
</article>'''

def university_card(u, c, programs):
    ps = [p for p in programs if p['university_id'] == u['id']]
    status = coverage_text(ps) if ps else '专业详情待收录'
    return f'''<article class="university-card" data-university-id="{u['id']}">{rank_badge(u)}<p class="catalog-eyebrow">{esc(c['name'])} · {esc(u['city'])}</p><h2>{link(route(c['id'], u['id']), u['name'])}</h2><p class="university-english">{esc(u['name_en'])}</p><p class="university-coverage">{status}</p>{link(route(c['id'],u['id']),"查看学校与专业入口 →","program-open")}</article>'''

def generate():
    countries, universities, programs = load_catalog()
    order = {'uk':0, 'australia':1, 'singapore':2, 'usa':3, 'canada':4, 'hong-kong':5}
    countries.sort(key=lambda c: (order.get(c['id'], 99), c['name_en']))
    cm, um = {c['id']:c for c in countries}, {u['id']:u for u in universities}
    universities.sort(key=lambda u: (u['qs_rank'], u['name_en']))
    programs.sort(key=lambda p: (um[p['university_id']]['qs_rank'], p['name_en']))
    program_university_count = len({p['university_id'] for p in programs})
    outputs = {}
    cards = '\n'.join(program_card(p, um[p['university_id']], cm[um[p['university_id']]['country_id']]) for p in programs[:24])
    home = front('QS 2027 大学与专业查询', True)
    home += '<div class="catalog-home" markdown="1">\n<p class="catalog-eyebrow">面向中国大陆学生的海外本科目录 · QS 2027</p>\n\n# 查大学，找专业\n\n点击国家或地区，筛选下方大学与专业；再次点击取消选择。学校按 QS 2027 世界大学排名排列，保留并列名次。\n\n'
    home += '<div class="country-grid">\n'
    for i,c in enumerate(countries):
        if i == 6:
            home += f'</div><details class="country-more"><summary>更多国家与地区（{len(countries)-6}）</summary><div class="country-grid">'
        us = [u for u in universities if u['country_id'] == c['id']]
        home += f'<a class="country-card country-{c["id"]}" data-country-filter="{c["id"]}" href="{BASE}{route(c["id"])}"><span class="country-en">{esc(c["name_en"])}</span><strong>{esc(c["name"])}</strong><span>{len(us)} 所大学 <b aria-hidden="true">↗</b></span></a>\n'
    home += '</div>' + ('</details>' if len(countries)>6 else '')
    home += '<div id="program-finder" data-catalog-url="assets/data/catalog-index.json">\n<div class="finder-heading"><h2>大学与专业资料库</h2><span>{} 个国家和地区 · {} 所大学 · {} 个专业条目</span></div>\n'.format(len(countries),len(universities),len(programs))
    home += f'<div class="catalog-view-controls" role="group" aria-label="查看大学或专业" hidden><button type="button" data-catalog-view="universities" aria-pressed="true" aria-controls="catalog-results">大学 · {len(universities)}</button><button type="button" data-catalog-view="programs" aria-pressed="false" aria-controls="catalog-results">专业 · {len(programs)}</button></div>'
    home += '''<form class="catalog-filters" role="search" aria-label="筛选大学与专业">
<label class="catalog-query"><span id="catalog-query-label">搜索学校或专业</span><input id="catalog-query" name="q" type="search" placeholder="例如：MIT、香港大学" autocomplete="off"></label>
<label>国家 / 地区<select id="catalog-country" name="country"><option value="">全部国家和地区</option>'''
    home += ''.join(f'<option value="{c["id"]}">{esc(c["name"])}</option>' for c in countries)
    home += '</select></label><label>大学<select id="catalog-university" name="university"><option value="">全部大学</option>' + ''.join(f'<option value="{u["id"]}" data-country="{u["country_id"]}">{esc(u["name"])}</option>' for u in universities) + '</select></label><label id="catalog-subject-label">专业方向<select id="catalog-subject" name="subject"><option value="">全部方向</option>' + ''.join(f'<option value="{esc(subject)}">{esc(subject)}</option>' for subject in sorted({s for p in programs for s in p.get('subjects',[p['subject']])})) + '</select></label><label id="catalog-depth-label">资料深度<select id="catalog-depth" name="depth"><option value="">全部条目</option><option value="detailed">含详细资料</option><option value="enriched">含部分资料</option><option value="directory">目录已核对</option></select></label><button type="reset">清除筛选</button></form>\n'
    home += '<noscript><style>.catalog-filters{display:none}</style><p>可通过国家入口和下面的大学、专业链接直接浏览。启用 JavaScript 后可使用即时筛选。</p></noscript>'
    home += f'<p class="catalog-status" id="catalog-status" role="status" aria-live="polite">收录 QS 2027 前 100 名的 {len(universities)} 所非中国大陆大学，按原始名次排序；“=”表示并列。</p><p id="catalog-empty" hidden></p><div id="catalog-results"><section id="catalog-universities"><h3 class="catalog-list-title">大学清单</h3><div class="university-grid">'
    home += '\n'.join(university_card(u,cm[u['country_id']],programs) for u in universities)
    home += f'</div></section><section id="catalog-programs"><h3 class="catalog-list-title">专业条目</h3><div class="program-grid">{cards}</div><p class="catalog-fallback-note">此处预览前 24 项。可进入各大学查看完整已收录清单，或启用筛选查询其余条目。</p></section></div><nav class="catalog-pagination" aria-label="查询结果分页" hidden><button type="button" data-page-step="-1">上一页</button><span class="catalog-page-position"></span><button type="button" data-page-step="1">下一页</button></nav>\n</div>\n\n'
    home += f'<div class="catalog-footnote"><strong>收录范围与数据口径</strong><p>QS 2027 榜单名次不大于 100 的共有 102 所；剔除中国大陆 6 所后收录 96 所，保留中国香港和中国台湾。大学排名与专业排名不同；入榜不表示面向所有申请者开放本科招生。专业资料目前覆盖 {program_university_count} 所大学、{coverage_text(programs)}。目录条目与详细资料分别计数，目录收录不表示招生、费用与毕业信息已核验。各校目录是否齐全见学校页。入学年度、费用年度和申请截止日期分别标注；已结束批次供参考。核验：2026-09-12。</p>' + link('about/catalog-data/','排名来源与数据说明') + ' · ' + link('tools/budget/','计算全程预算') + ' · ' + link('start/undergraduate/','申请准备指南') + '</div>\n</div>\n'
    outputs['docs/index.md'] = home
    directory = front('国家与地区', True) + '# 按国家与地区查大学\n\n收录 QS 2027 前 100 名的非中国大陆大学。选择所在地，查看大学排名与资料收录情况。\n\n<div class="country-grid">'
    for c in countries:
        count = sum(u['country_id'] == c['id'] for u in universities)
        directory += f'<a class="country-card" href="{BASE}{route(c["id"])}"><span class="country-en">{esc(c["name_en"])}</span><strong>{esc(c["name"])}</strong><span>{count} 所大学</span></a>'
    outputs['docs/catalog/index.md'] = directory + '</div>\n'
    index = []
    for c in countries:
        us = [u for u in universities if u['country_id'] == c['id']]
        body = front(c['name']+'大学与专业', True) + crumbs([('', '大学与专业'),(None,c['name'])])
        body += f'# {c["name"]}大学与专业\n\n先选择大学，再进入专业查看入学条件、国际生学费和毕业生情况。当前收录 {len(us)} 所 QS 2027 前 100 名大学；“=”表示并列。专业详情收录情况见学校卡片。\n\n<div class="university-grid">\n'
        body += '\n'.join(university_card(u,c,programs) for u in us) + '</div>\n\n'
        body += link('?country='+c['id']+'#program-finder','筛选这里的大学与专业 →','md-button') + '\n'
        outputs['docs/'+route(c['id'])+'index.md'] = body
        for u in us:
            ps = [p for p in programs if p['university_id']==u['id']]
            body = front(u['name'],True) + crumbs([('', '大学与专业'),(route(c['id']),c['name']),(None,u['name'])])
            body += f'# {u["name"]}\n\n<p class="university-title-en">{esc(u["name_en"])}</p><p class="university-location">{esc(c["name"])} · {esc(u["city"])}</p>\n\n'
            if u.get('aliases'): body += '<p class="university-aliases">常用名称或简称：' + esc(' · '.join(u['aliases'])) + '</p>\n\n'
            body += f'<p class="university-ranking">{rank_badge(u)} <a href="{RANKING["source_url"]}">QS 官方榜单 ↗</a></p>\n\n'
            body += '排名口径：QS World University Rankings 2027（大学综合排名）；“=”表示并列。核验日期：2026-09-12。' + link('about/catalog-data/','查看范围与排名更正说明') + '\n\n'
            body += f'<p><a class="md-button" href="{esc(u["website"])}">大学官方网站 ↗</a></p>\n\n## 专业与申请资料\n\n'
            if ps:
                body += f'{coverage_text(ps)}。入学条件、学费和毕业调查范围按具体项目查看。\n\n' + link('?view=programs&university='+u['id']+'#program-finder','搜索、筛选这所大学的专业 →','md-button') + '\n\n<div class="university-program-list">\n' + '\n'.join('<article>'+link(route(c['id'],u['id'],p['id']),p['name'])+'<small>'+esc(p.get('degree_label') or p['name_en'])+' · '+('仅补学校共用资料' if p.get('research_scope')=='school' else {'detailed':'含详细资料','enriched':'部分专业资料已核实','directory':'目录已核对 · 详情待补'}[p['detail_status']])+'</small></article>' for p in ps) + '</div>\n\n'
            else:
                body += '目前已收录学校身份、所在地、QS 2027 排名及官网入口，**专业详情待收录**。可先从大学官网查找本科课程与国际生招生入口。\n\n'
                body += '| 资料 | 当前状态 |\n| --- | --- |\n| 本科专业与学制 | 待按具体课程核验 |\n| 中国大陆学生入学条件 | 待核验；需区分高考、国际课程与其他资格 |\n| 国际生学费 | 待取得具体专业、入学年度和币种 |\n| 毕业生情况 | 待取得课程或学科的调查范围与年份 |\n\n'
            if u.get('profile'):
                body += profile_markdown(u['profile'], esc)
            if u.get('catalog_coverage'):
                coverage = u['catalog_coverage']
                label = '已完成所列官方目录范围的对账' if coverage['status'] == 'complete' else '官方目录仍在补齐'
                body += f'## 专业目录覆盖记录\n\n**{label}**，共 {coverage["count"]} 项；这不是全字段详情的完成状态。\n\n'
                body += f'<p><strong>统计范围：</strong>{esc(coverage["scope"])}</p>\n\n'
                body += f'<p><strong>对账方法：</strong>{esc(coverage["method"])}</p>\n\n'
                body += f'<p><strong>排除项：</strong>{esc(coverage["exclusions"])}</p>\n\n'
                if coverage.get('gaps'):
                    body += '**尚未解决的目录缺口：**\n\n' + '\n'.join('- '+esc(str(gap)) for gap in coverage['gaps']) + '\n\n'
                for source in coverage['sources']:
                    body += f'- [官方目录来源]({source["url"]})\n'
                body += '\n'
            body += '大学综合排名不能代替专业选择，也不能据此推定本科招生资格、费用或个人毕业结果。\n'
            outputs['docs/'+route(c['id'],u['id'])+'index.md'] = body
            for p in ps:
                body = front(u['name']+' · '+p['name'], program_context={'catalog_program': True, 'catalog_country': c['name'], 'catalog_country_url': BASE+route(c['id']), 'catalog_university': u['name'], 'catalog_university_url': BASE+route(c['id'],u['id'])}) + crumbs([('','大学与专业'),(route(c['id']),c['name']),(route(c['id'],u['id']),u['name']),(None,p['name'])])
                body += f'<p class="catalog-eyebrow">{esc(u["name"])} · {esc(p["degree"])} · {esc(p["subject"])}</p>\n\n# {p["name"].strip()}\n\n<p class="program-title-en">{esc(p["name_en"])}</p>\n\n'
                body += '<div class="program-at-a-glance">' + ''.join(f'<div><span>{esc(label)}</span><strong>{esc(value)}</strong></div>' for label,value in [('入学年度',p['intake']),('学制',p['duration']),(p.get('tuition_label','国际生学费'),p['tuition_summary'])]) + '</div>\n\n'
                body += f'<p class="program-location"><strong>校区：</strong>{esc(p["campus"])} · <strong>授课语言：</strong>{esc(p["language"])}</p>\n\n'
                body += '<nav class="program-jumps" aria-label="专业详情章节">' + ''.join(f'<a href="#{key}">{title}</a>' for key,title in SECTIONS) + '</nav>\n\n'
                if p['detail_status'] != 'detailed':
                    body += inventory_markdown(p, esc)
                else:
                    for key,title in SECTIONS:
                        body += f'## {title} {{#{key}}}\n\n'
                        for fact in p['sections'][key]:
                            body += f'### {fact["label"]}\n\n<p class="catalog-fact">{esc(fact["text"]).replace(chr(10),"<br>")}</p>\n<p class="fact-sources">'
                            body += ' · '.join(f'<a href="#source-{sid}">依据 {list(s["id"] for s in p["sources"]).index(sid)+1}</a>' for sid in fact['source_ids']) + '</p>\n\n'
                    body += '## 官方来源与核验记录 {#sources}\n\n'
                    body += f'资料核验：**{p["checked_at"]}**。课程招生年份与毕业调查年份分别记录；历史毕业结果不表示未来个人结果。\n\n'
                    for i,s in enumerate(p['sources'],1):
                        body += f'<div class="catalog-source" id="source-{s["id"]}"><span class="source-number">{i:02d}</span><div><a href="{esc(s["url"])}">{esc(s["title"])} ↗</a><p>{esc(s["supports"])}</p><small>{esc(urlsplit(s["url"]).netloc)} · 核验 {s["checked_at"]}</small></div></div>\n'
                body += '\n' + link(route(c['id'],u['id']),'← 返回'+u['name']) + ' · ' + link('tools/budget/','用已确认费用计算全程预算') + '\n'
                outputs['docs/'+route(c['id'],u['id'],p['id'])+'index.md'] = body
                index.append({k:p[k] for k in ['id','university_id','name','name_en','degree','subject','intake','duration','campus','language','entry_summary','tuition_summary','outcomes_summary','detail_status']} | {'subjects':p.get('subjects',[p['subject']]),'degree_label':p.get('degree_label'),'research_scope':p.get('research_scope'),'qs_rank':u['qs_rank'],'qs_rank_display':u['qs_rank_display'],'country_id':c['id'],'country_name':c['name'],'university_name':u['name'],'university_name_en':u['name_en'],'aliases':u.get('aliases',[]),'url':route(c['id'],u['id'],p['id'])})
    exclusion_file = ROOT/'data/catalog-exclusions.json'
    for item in json.loads(exclusion_file.read_text()) if exclusion_file.exists() else []:
        u = um[item['university_id']]; c = cm[u['country_id']]
        assert item['id'] not in {p['id'] for p in programs}, 'Excluded item remains in the live catalog'
        body = front(item['name_en']+' · 收录范围说明', program_context={'catalog_program': True, 'catalog_country': c['name'], 'catalog_country_url': BASE+route(c['id']), 'catalog_university': u['name'], 'catalog_university_url': BASE+route(c['id'],u['id'])})
        body += '# '+item['name_en'].strip()+'\n\n> **此项目已移出本科专业清单。** 旧链接保留，供查阅更正说明。\n\n'+esc(item['reason'])+'\n\n'
        if item.get('replacement_inventory_id'):
            replacement = next(p for p in programs if p['id'] == item['replacement_inventory_id'])
            assert replacement['university_id'] == u['id'], 'Replacement must belong to the same university'
            body += link(route(c['id'],u['id'],replacement['id']), '查看现行专业：'+replacement['name'])+'\n\n'
        body += link(route(c['id'],u['id']), '返回'+u['name']+'的本科专业清单')+'\n\n## 官方依据\n\n'
        for source in item['sources']:
            assert re.fullmatch(r'[a-f0-9]{64}', source['sha256'])
            body += f'- <a href="{esc(source["url"])}">{esc(source["title"])}</a>（核对：{esc(source["checked_at"]) }）\n'
        outputs['docs/'+route(c['id'],u['id'],item['id'])+'index.md'] = body
    university_index = [{k:v for k,v in u.items() if k not in ('catalog_coverage','profile')} | {'country_name':cm[u['country_id']]['name'], 'program_count':sum(p['university_id']==u['id'] for p in programs), 'detailed_count':sum(p['university_id']==u['id'] and p['detail_status']=='detailed' for p in programs), 'url':route(u['country_id'],u['id'])} for u in universities]
    outputs['docs/assets/data/catalog-index.json'] = json.dumps({'universities':university_index,'programs':index,'ranking':{k:v for k,v in RANKING.items() if k!='rows'}},ensure_ascii=False,separators=(',', ':'))+'\n'
    nav = ['  - 全部国家和地区: catalog/index.md']
    for c in countries:
        nav.append(f'  - {c["name"]}:')
        nav.append(f'      - 大学列表: {route(c["id"])}index.md')
        for u in [u for u in universities if u['country_id']==c['id']]:
            nav += [f'      - {u["name"]}:', f'          - 大学概览: {route(c["id"],u["id"])}index.md']
    config = (ROOT/'mkdocs.yml').read_text()
    config = re.sub(r'  # CATALOG_NAV_START\n.*?  # CATALOG_NAV_END', '  # CATALOG_NAV_START\n'+'  - 国家与地区:\n'+'\n'.join('    '+line for line in nav)+'\n  # CATALOG_NAV_END',config,flags=re.S)
    outputs['mkdocs.yml'] = config
    return outputs, (len(countries),len(universities),len(programs))

if __name__ == '__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    outputs, counts = generate()
    outdated=[]
    for name,content in outputs.items():
        path=ROOT/name
        if not path.exists() or path.read_text()!=content:
            if args.check: outdated.append(name)
            else: path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content)
    expected={str((ROOT/name).resolve()) for name in outputs if name.startswith('docs/catalog/')}
    unexpected=[str(p.relative_to(ROOT)) for p in (ROOT/'docs/catalog').rglob('*.md') if str(p.resolve()) not in expected]
    assert not unexpected, f'Orphaned generated pages: {unexpected}'
    if outdated: raise SystemExit('Catalog output is stale: '+', '.join(outdated))
    print(f'Catalog {"checked" if args.check else "rendered"}: {counts[0]} countries, {counts[1]} universities, {counts[2]} sourced programs')
